build:
  cuda_version: "12.1.1"
  python_packages:
    - "accelerate==0.31.0"
    - "diffusers==0.29.1"
    - "transformers==4.41.2"
    - "torch==2.3.0"
    - "sentencepiece==0.2.0"
    - "protobuf==3.20.0"
